name: menue
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/biryani.jpg
    - assets/images/burger.jpg
    - assets/images/pasta.jpg
    - assets/images/pizza.jpg
    - assets/images/suchi.jpg  
    - assets/images/FrenchFrise.jpeg


